spring.application.name=spring_hw001

spring.datasource.url=jdbc:postgresql://localhost:5432/person_db
spring.datasource.username=postgres
spring.datasource.password=phatsa08
spring.datasource.driver-class-name=org.postgresql.Driver
